# GitHub Pages configuration for DocC documentation
name: github-pages

on:
  workflow_run:
    workflows: ["Build and Deploy DocC Documentation"]
    types:
      - completed

permissions:
  pages: write
  id-token: write

environment:
  name: github-pages
  url: ${{ steps.deployment.outputs.page_url }}

concurrency:
  group: "pages"
  cancel-in-progress: false
